// Generated by build/sw-plugin.ts — do not edit.
const CACHE = "bailiwick-af238866b734";
const PRECACHE = [
  "./",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/index-DFriElID.css",
  "./assets/index-mZS8divZ.js",
  "./index.html",
  "./manifest.webmanifest"
];
const INDEX = new URL('index.html', self.location.href).href;

// The precache is keyed purely by URL. Servers commonly send "Vary: Origin",
// and a module script or stylesheet is fetched with an Origin header that the
// precache request did not carry — so without ignoreVary every asset would miss
// the cache and the game would only work offline as a blank page.
const MATCH = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Navigations always resolve to the cached shell so the game opens offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match(INDEX, MATCH).then((cached) => cached || fetch(request)),
    );
    return;
  }

  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
