// Generated by build/sw-plugin.ts — do not edit.
const CACHE = "bailiwick-89b0b6d9adc6";
const PRECACHE = [
  "./",
  "./assets/dom-2yE6n84i.css",
  "./assets/dom-CTvgmLn3.js",
  "./assets/game-DIfdUT3h.js",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/title-BsUCacmO.js",
  "./game/",
  "./game/index.html",
  "./index.html",
  "./manifest.webmanifest"
];
// Two pages now: the title at the root and the game one level under it. A
// navigation has to be answered with the page it actually asked for, or the
// game would open on the title screen whenever the network was away.
const TITLE = new URL('index.html', self.location.href).href;
const GAME = new URL('game/index.html', self.location.href).href;
const GAME_PATH = new URL('game/', self.location.href).pathname;

// The precache is keyed purely by URL. Servers commonly send "Vary: Origin",
// and a module script or stylesheet is fetched with an Origin header that the
// precache request did not carry — so without ignoreVary every asset would miss
// the cache and the game would only work offline as a blank page.
const MATCH = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Navigations resolve to whichever cached page was asked for, so both open
  // with no connection at all.
  if (request.mode === 'navigate') {
    const wanted = new URL(request.url).pathname.startsWith(GAME_PATH) ? GAME : TITLE;
    event.respondWith(caches.match(wanted, MATCH).then((cached) => cached || fetch(request)));
    return;
  }

  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
